bayesian:
  default_sigma: 3.0
  thres_win_size: 5
  thres_reduce_func: "mean"


stats_detector:
  default_sigma: 4.0
  thres_win_size: 5
  thres_reduce_func: "mean"
  score_win_size: 3
  anomaly_threshold: 0.5
  sigmas:
    Row_Lock_Timeout_Errors: 5.0
    JVM_Compiler_Thread_Usage: 5.0
    Hbase_Connectivity_for_SuperPod: 3.0
    ORA_Concurrency_Wait_Time: 5.0
    APT: 5.0
    Log_File_Sync: 5.0
  manual_thresholds:
    Connection_Pool_Errors:
      lower: 0.0
      upper: 10.0